"""
report_generator.py
====================
Exports the AI-generated engineering report (plus key building statistics)
to Markdown and PDF. Uses ReportLab for PDF generation — a pure open-source
library, keeping the entire stack free of proprietary/cloud dependencies.

Author: Digital Twin Research Lab (prototype)
"""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
)

from llm_engine import REPORT_SECTIONS

BRAND_PRIMARY = colors.HexColor("#0B3D91")
BRAND_ACCENT = colors.HexColor("#2CA6A4")


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------

def generate_markdown_report(building_stats: dict, sections: dict,
                              model_name: str, building_name: str = "Untitled Building") -> str:
    """Assemble a full Markdown report combining stats + LLM narrative sections."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []
    lines.append(f"# HVAC Engineering Copilot — Report")
    lines.append(f"**Building / Dataset:** {building_name}  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**LLM Model:** {model_name} (local, via Ollama)  ")
    lines.append("\n---\n")

    lines.append("## Key Operational Statistics\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    for key, value in building_stats.items():
        pretty_key = key.replace("_", " ").title()
        lines.append(f"| {pretty_key} | {value} |")
    lines.append("\n---\n")

    for section_title in REPORT_SECTIONS:
        content = sections.get(section_title, "_Not provided._")
        lines.append(f"## {section_title}\n")
        lines.append(content)
        lines.append("")

    lines.append("\n---\n")
    lines.append("_This report was generated by an AI research prototype (Digital Twin "
                  "Research Lab) using a locally-hosted Llama 3.1 model. It is intended "
                  "for research and demonstration purposes and should be reviewed by a "
                  "qualified engineer before any operational decisions are made._")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF export
# ---------------------------------------------------------------------------

def _pdf_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportTitle", fontSize=20, leading=24,
                               textColor=BRAND_PRIMARY, spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="SubTitle", fontSize=10, leading=14,
                               textColor=colors.grey, spaceAfter=14))
    styles.add(ParagraphStyle(name="SectionHeader", fontSize=13, leading=16,
                               textColor=BRAND_PRIMARY, spaceBefore=14, spaceAfter=6,
                               fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="BodyTextCustom", fontSize=9.5, leading=14,
                               spaceAfter=6, fontName="Helvetica"))
    styles.add(ParagraphStyle(name="Footer", fontSize=7.5, leading=10,
                               textColor=colors.grey))
    return styles


def _markdown_bullets_to_paragraphs(text: str, style) -> list:
    """Very small helper to turn simple '- bullet' markdown lines into Paragraphs."""
    flowables = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith(("- ", "* ")):
            flowables.append(Paragraph(f"&bull;&nbsp;&nbsp;{stripped[2:]}", style))
        else:
            flowables.append(Paragraph(stripped, style))
    if not flowables:
        flowables.append(Paragraph("_Not provided._", style))
    return flowables


def generate_pdf_report(building_stats: dict, sections: dict, model_name: str,
                         building_name: str = "Untitled Building") -> bytes:
    """
    Render the full report (stats table + narrative sections) to a PDF and
    return the raw bytes (suitable for st.download_button).
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
        title="HVAC Engineering Copilot Report",
    )
    styles = _pdf_styles()
    story = []

    # --- Title block ---------------------------------------------------
    story.append(Paragraph("HVAC Engineering Copilot", styles["ReportTitle"]))
    story.append(Paragraph("Digital Twin Research Lab — AI-Generated Engineering Report",
                            styles["SubTitle"]))
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    story.append(Paragraph(
        f"Building / Dataset: <b>{building_name}</b> &nbsp;|&nbsp; "
        f"Generated: {now} &nbsp;|&nbsp; Model: {model_name} (local via Ollama)",
        styles["BodyTextCustom"]
    ))
    story.append(HRFlowable(width="100%", color=BRAND_ACCENT, thickness=1, spaceAfter=10))

    # --- Stats table -----------------------------------------------------
    story.append(Paragraph("Key Operational Statistics", styles["SectionHeader"]))
    table_data = [["Metric", "Value"]]
    for key, value in building_stats.items():
        table_data.append([key.replace("_", " ").title(), str(value)])

    table = Table(table_data, colWidths=[8 * cm, 8 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)
    story.append(Spacer(1, 10))

    # --- Narrative sections -----------------------------------------------
    for section_title in REPORT_SECTIONS:
        content = sections.get(section_title, "_Not provided._")
        story.append(Paragraph(section_title, styles["SectionHeader"]))
        story.extend(_markdown_bullets_to_paragraphs(content, styles["BodyTextCustom"]))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=colors.lightgrey, thickness=0.75))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This report was generated by an AI research prototype (Digital Twin Research Lab) "
        "using a locally-hosted Llama 3.1 model. It is intended for research and demonstration "
        "purposes and should be reviewed by a qualified engineer before any operational decisions "
        "are made.",
        styles["Footer"]
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
